In [1]:
## Load modules

# Standard modules
import pandas as pd
import numpy as np
import sys

# Preprocessing modules
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler,\
 OneHotEncoder, LabelEncoder, OrdinalEncoder

# Train-test split module
from sklearn.model_selection import train_test_split

# Classifier modules
from sklearn.ensemble import RandomForestClassifier

# Regression modules
from sklearn.ensemble import RandomForestRegressor

# Model selection modules
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold, GridSearchCV

# Pipeline module
from sklearn.pipeline import Pipeline

# Imputation modules
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer, IterativeImputer
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_selector as selector

# Performance metric modules
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Plotting modules
import matplotlib.pyplot as plt
import matplotlib.cm as cm
plt.style.use('dark_background')
%matplotlib inline
plt.rcParams['figure.figsize'] = (4.0, 4.0) # set default size of plots

pd.options.display.max_columns = None

# Module for categorical variables
from pandas.api.types import CategoricalDtype

# Modules for building custom encoders and transformers
from sklearn.base import BaseEstimator, TransformerMixin

# TensorFlow modules
import tensorflow as tf
print(tf.__version__)

from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Input, Dense, Conv2D, MaxPooling2D,Flatten, Dropout, Lambda, Reshape, BatchNormalization
from tensorflow.keras import backend as K
from tensorflow.keras.utils import plot_model

2.14.0

In [2]:
## Mount Google drive folder if running in Colab
if('google.colab' in sys.modules):
    from google.colab import drive
    drive.mount('/content/drive', force_remount = True)
    # Change path below starting from /content/drive/MyDrive/Colab Notebooks/
    # depending on how data is organized inside your Colab Notebooks folder in
    # Google Drive
    DIR = '/content/drive/MyDrive/Colab Notebooks/MAHE/MSIS Coursework/EvenSem2024MAHE'
    DATA_DIR = DIR+'/Data/'
else:
    DATA_DIR = 'D:/Deep_Learning_Workshop/Codes/RNN_LSTM/'

In [3]:
## Load Sales Data
file = DATA_DIR+'sales.csv'
df = pd.read_csv(file, sep = ',', header = 0, index_col = 0)
df.head(5)

              RSXFSN
DATE
1992-01-01  130683.0
1992-02-01  131244.0
1992-03-01  142488.0
1992-04-01  147175.0
1992-05-01  152420.0

In [4]:
## Generte sequence data
data_trend = np.arange(1, 21)
df_trend = pd.DataFrame(data_trend, columns = ['trend'])
df_trend

    trend
0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8
8       9
9      10
10     11
11     12
12     13
13     14
14     15
15     16
16     17
17     18
18     19
19     20

In [ ]:
#Prepare data for univariate time series forecasting

In [5]:
## Generate another sequence data
data_trend2 = np.array([np.arange(1, 21), np.arange(20, 0, -1)]).transpose()
df_trend2 = pd.DataFrame(data_trend2, columns = ['trend1','trend2'])
df_trend2

    trend1  trend2
0        1      20
1        2      19
2        3      18
3        4      17
4        5      16
5        6      15
6        7      14
7        8      13
8        9      12
9       10      11
10      11      10
11      12       9
12      13       8
13      14       7
14      15       6
15      16       5
16      17       4
17      18       3
18      19       2
19      20       1

In [ ]:
# Construct time series from a single sequence

In [11]:
df_trend2.head(5)

   trend1  trend2
0       1      20
1       2      19
2       3      18
3       4      17
4       5      16

In [ ]:
# Construct time series from a multiple sequences
def prep_timeseries2(x, y, n_steps=1):
    x_ts, y_ts = [], []
    for i in range(len(x) - n_steps):
        x_ts.append(x.iloc[i: (i+n_steps)].values)
        y_ts.append(y.iloc[i+n_steps])
    return np.array(x_ts), np.array(y_ts)

In [8]:
## User defined function to prepare the univariate time series data
def prep_timeseries(x, n_steps = 1):
    x_ts, y_ts = [], []
    for i in range(len(x) - n_steps):
        x_ts.append(x.iloc[i: (i+n_steps)].values)
        y_ts.append(x.iloc[i+n_steps])
    return np.array(x_ts), np.array(y_ts)

In [9]:
## Convert to time series dimension: [samples, n_steps, n_features]
n_steps = 3
X, y = prep_timeseries(df_trend, n_steps)

In [10]:
print(X.shape, y.shape)

(17, 3, 1) (17, 1)

In [14]:
## Convert to time series dimension: [samples, n_steps, n_features]
n_steps = 3
X, y = prep_timeseries(df_trend2.trend1, n_steps)

In [15]:
print(X.shape, y.shape)

(17, 3) (17,)